### ISSUE TITLE
Moving to large-scale SCRUM-friendly GIT-workflow

### ISSUE THREAD

**Issue by etienne-freshworks** [bcgov/fwben#84]
This is primarily a discussion that needs to happen with the other teams.  We need to adopt a git workflow/branching model that is better suited to our growing teams.  Recommendations and reasoning behind this (and discussion points) can be found here:

https://docs.google.com/document/d/1Q6-rOGDPgBl1lmWQgS9CLZoVwGkKqmj9CuEAzb2cgiI/edit?usp=sharing

Outside of making a decision as a team, there will be some technical tasks that will be required to put this into action.  This should involve creating the greater (project-level) branches, establishing branch-permissions within github, and running test PR/Merges to ensure that its been properly setup before any significant development against it starts.

Acceptance Criteria:
- Branches are cut, and branch-permissions are established in github
- Test Pull Requests / Merges have been completed to prove that the cuts were done properly.
- Documentation

**Comment by ConradGustafson** [comment]
We learned a bunch on this. The plan is to stay very aligned with the Apis team by working on master. 
Each team (or individual) must create a FORK of the repo that they need to work on. When the work is done, it's a pull request into the lear master. 
This is a very primitive workflow for now, but it is what the teams have agreed upon, so that's the extent of this ticket for now.
